### ISSUE TITLE
GitHub link in settings > about links to the archived repo

### ISSUE THREAD

**Issue by Wojtaz0w** [pixkk/VueTube#11]
### Steps to reproduce

Go to VueTube settings, click about, clink on github link. Boom, you're on the old repo (not this fork)

### Expected behavior

The link is to the new, forked repo

### Actual behavior

It links to the old repo (archived)

### VueTube version

8d9bd12

### Android version

15

### Device

Pixel 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by pixkk** [comment]
Hello. Try this version - https://github.com/pixkk/VueTube/actions/runs/11139122292/artifacts/2004512133 (from https://github.com/pixkk/VueTube/actions/runs/11139122292/job/30955278883)

**Comment by Wojtaz0w** [comment]
> Hello. Try this version - https://github.com/pixkk/VueTube/actions/runs/11139122292/artifacts/2004512133 (from https://github.com/pixkk/VueTube/actions/runs/11139122292/job/30955278883)

It's working :)
Closing the issue as resolved
