### ISSUE TITLE
😒

### ISSUE THREAD

**Issue by senolfndk** [pixkk/VueTube#2]
### Steps to reproduce

videos are not loading

### Expected behavior

videos are not loading

### Actual behavior

videos are not loading

### VueTube version

70acb51

### Android version

Android 12

### Device

Samsung Galaxy A21s

### Other details

![Screenshot_20240320-222406_VueTube](https://github.com/pixkk/VueTube/assets/52818836/47f2ddbe-4c2c-4be8-970b-2d5096d1f563)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by pixkk** [comment]
Try unstable version - https://github.com/pixkk/VueTube?tab=readme-ov-file#install

**Comment by senolfndk** [comment]
> Kararsız sürümü deneyin - https://github.com/pixkk/VueTube?tab=readme-ov-file#install
these are old version

**Comment by senolfndk** [comment]
this has the same problem https://github.com/pixkk/VueTube/actions/runs/8364132011

**Comment by pixkk** [comment]
Okay, i need your useragent to reproduce the bug - https://www.whatismybrowser.com/detect/what-is-my-user-agent/
