### ISSUE TITLE
Links are down

### ISSUE THREAD

**Issue by kittenvr** [pixkk/VueTube#3]
### Steps to reproduce

Go to read me
Click view screenshots on website 

### Expected behavior

I see website

### Actual behavior

Not available 

### VueTube version

/

### Android version

14

### Device

Samsung Galaxy s21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by pixkk** [comment]
Yes, unfortunately, the original site (or most likely the domain) was not renewed, so for now I recommend using the links that are located at: https://github.com/pixkk/VueTube?tab=readme-ov-file#install

**Comment by kittenvr** [comment]
> Yes, unfortunately, the original site (or most likely the domain) was not renewed, so for now I recommend using the links that are located at: https://github.com/pixkk/VueTube?tab=readme-ov-file#install

Could you maybe replace the links with GitHub pages

**Comment by pixkk** [comment]
New site (for this fork) - https://pixkk.com/

**Comment by pixkk** [comment]
> > New site (for this fork) - [pixkk.com](https://pixkk.com/)
> 
> did you host the screenshots on there?

https://pixkk.com/info/screenshots.html
