### ISSUE TITLE
VueTube stopped working

### ISSUE THREAD

**Issue by pixkk** [pixkk/VueTube#8]
So, i have some not good news.

As I once said, the transition to server rendering is a matter of time. And unfortunately (I’ll explain why now) that time has come. Forcibly. 

As I wrote earlier, viewing channel information for European residents is impossible without “confirming” the cookies.Previously, this was the only problem with the application. Now YouTube has strictly limited the sending of requests - it has set CORS. If in a browser on a computer it is possible to bypass this by installing an extension in the browser, then in mobile applications it is not. 

![image](https://github.com/user-attachments/assets/f0acd5cb-e8f9-4995-ade0-1192478bc6e2)

There are two options for solving the problem - rewriting the application (almost from scratch) for server side rendering or, unfortunately, admitting that ViewTube can only work as a browser application on a computer with "crutches"  (with CORS bypass extensions) and further development for mobile devices is impossible.

In the case of rewriting to server rendering, several problems arise - the presence of a server (relatively easy to solve for Android, sucks for iOS) and relatively long each application launch.

In terms of time, I don’t know when I will be able to do all this and whether I can do it at all. All the information above was given by me for reflection, so I’m (possibly) waiting for your comments.

**Comment by pixkk** [comment]
Closed

**Comment by DaRandomCube** [comment]
um how was it solved?

**Comment by georgiy-o** [comment]
> um how was it solved?

It may have been a YouTube bug, so we didn't edit a single line of code to fix it.

**Comment by pixkk** [comment]
> um how was it solved?

It may have been a YouTube bug, so we didn't edit a single line of code to fix it.
