### ISSUE TITLE
[FR] Player Enhancement

### ISSUE THREAD

**Issue by brnwlshubh** [pixkk/VueTube#9]
### Describe your suggested feature

Volume and Brightness Slider option in player

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by pixkk** [comment]
Please, check this build -> https://github.com/pixkk/VueTube/actions/runs/10698250092

**Comment by brnwlshubh** [comment]
Thanks for fulfilling the request.
